import Layout from '@/components/Layout';
import Head from 'next/head';
import Image from 'next/image';
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { useRouter } from "next/router";
import AboutUs from '@/components/AboutUs';
import OurServices from '@/components/OurServices';
import Gallery from '@/components/Gallery';
import Team from '@/components/Team';
import Mentor from '@/components/Mentor';
// import Exe from '@/components/Exe';
import WhyUs from '@/components/WhyUs';
import Testimonials from '@/components/Testimonials';
import Contact from '@/components/Contact';
// import { LinkArrow } from '@/components/Icons';
// import HireMe from '@/components/HireMe';
// import transitionEffect from "@/components/transitionEffect";



export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Wallasteve Auto</title>
        <meta
          name="description"
          content="Generated by Wallasteve Auto & Mexhanics Engineering"
        />
      </Head>
      {/* <transitionEffect /> */}
      <main
        className="flex  min-h-screen xl:min-h-[50vh] m-0 items-center w-full text-dark sm:items-start dark:text-light 2xl"
        style={{
          background: "url(../images/hero.png)",
          backgroundPosition: "center center",
          backgroundSize: "cover",
        }}
      >
        <Layout
          className="!bg-transparent text-light xl:min-h-[50vh] flex justify-start items-center  xl:min-h-[100vh] rt:min-h-[100vh] 
         sm:min-h-[100vh]  xl:justify-start pt-2 md:pt-16 sm:pt-20 "
        >
          <div
            className="!bg-transparent w-1/2 md:w-1/2 sm:w-full rt:w-full flex flex-col items-center mt-20 self-center lg:items-center  
            lg:w-full xl:w-2/3 lg:text-center xl:self-start lg:mt-40"
          >
            <AnimatedText
              text="Welcome to Wallasteve Auto & Mechanical Engineering"
              className="!text-4xl !text-left xl:!text-4xl lg:!text-center text-light lg:!text-3xl md:!text-2xl sm:!text-3xl 
              xs:mt-10 sm:mt-0 rt:mt-8"
            />
            <p className="my-4 text-base font-medium sm:hidden  rt:hidden md-hidden lg:hidden xl:block">
              At Wallasteve Auto & Mechanics, we pride ourselves on providing
              top-notch automotive to our valued customers. With years of
              expirience in the industry, our team of skilled technicians is
              committed to delivering exceptional services, quality,
              workmanship, and complete customer satisfiction
            </p>
            <div className="flex items-center self-start lg:self-center mt-2 sm:mt-5 ">
              <Link
                href="/about"
                className="text-md font-medium capitalize text-gold dark:text-goldD  hover:underline underline-offset-2"
              >
                Learn more
              </Link>
            </div>
          </div>
        </Layout>
        {/* <HireMe /> */}
      </main>
      <main className='!bg-light'>
        <AboutUs />
        <OurServices />
        <Gallery />
        <WhyUs/>
        <Mentor/>
        <Team />
        <Testimonials/>
        <Contact/>
        {/* <Exe/> */}
      </main>
    </>
  );
}
